/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre.toto;

public class App {
    public String getGreeting() {
        return "Bonjour le monde #";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
